---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by InTheObscure.
--- DateTime: 26.08.2025 17:47
---
require("sound-util")
require("circuit-connector-sprites")
require("util")
require("__space-age__.prototypes.entity.circuit-network")
require("__space-age__.prototypes.entity.space-platform-hub-cockpit")

local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")
local space_age_sounds = require("__space-age__.prototypes.entity.sounds")
local meld = require("meld")
local simulations = require("__space-age__.prototypes.factoriopedia-simulations")
local procession_graphic_catalogue_types = require("__base__/prototypes/planet/procession-graphic-catalogue-types")

local biochamber_pictures = require("__space-age__.prototypes.entity.biochamber-pictures")

data:extend(
    {   ------------------------ Здания ------------------------
        ---advanced-oil-refinery---
        {
            type = "assembling-machine",
            name = "advanced-oil-refinery",
            icon = "__space-age-addon__/graphics/icons/advanced-oil-refinery.png",

            flags = {"placeable-neutral", "player-creation"},
            minable = {
                mining_time = 0.2,
                result = "advanced-oil-refinery"
            },
            fast_replaceable_group = "oil-refinery",
            max_health = 350,
            corpse = "oil-refinery-remnants",
            dying_explosion = "oil-refinery-explosion",
            icon_draw_specification = {
                scale = 2,
                shift = {0, -0.3}
            },
            circuit_wire_max_distance = assembling_machine_circuit_wire_max_distance,
            circuit_connector = circuit_connector_definitions["oil-refinery"],
            collision_box = {{-2.4, -2.4}, {2.4, 2.4}},
            collision_mask = {
                layers = {
                    item = true,
                    object = true,
                    player = true,
                    water_tile = true,
                    elevated_rail = true,
                    is_object = true,
                    is_lower_object = true,
                    meltable = true
                }
            },
            selection_box = {{-2.5, -2.5}, {2.5, 2.5}},
            damaged_trigger_effect = hit_effects.entity(),
            drawing_box_vertical_extension = 0.3,
            module_slots = 6,
            icons_positioning = {{
                inventory_index = defines.inventory.furnace_modules,
                shift = {0, 0.95},
                max_icons_per_row = 3
            }},
            icon_draw_specification = {
                scale = 2,
                shift = {0, -0.3}
            },
            allowed_effects = {"consumption", "speed", "productivity", "pollution"},
            crafting_categories = {"oil-processing", "oil-processing-or-advanced-oil-processing"},
            crafting_speed = 2,
            energy_source = {
                type = "electric",
                usage_priority = "secondary-input",
                emissions_per_minute = {
                    pollution = 4
                }
            },
            energy_usage = "680kW",

            graphics_set = {
                animation = make_4way_animation_from_spritesheet({
                    layers = {{
                        filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery.png",
                        width = 386,
                        height = 430,
                        shift = util.by_pixel(0, -7.5),
                        scale = 0.5
                    }, {
                        filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery-shadow.png",
                        width = 674,
                        height = 426,
                        shift = util.by_pixel(82.5, 26.5),
                        draw_as_shadow = true,
                        scale = 0.5
                    }}
                }),

                working_visualisations = {{
                    fadeout = true,
                    constant_speed = true,
                    north_position = util.by_pixel(34, -65),
                    east_position = util.by_pixel(-52, -61),
                    south_position = util.by_pixel(-59, -82),
                    west_position = util.by_pixel(57, -58),
                    animation = {
                        filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery-fire.png",
                        line_length = 10,
                        width = 40,
                        height = 81,
                        frame_count = 60,
                        animation_speed = 0.75,
                        scale = 0.5,
                        draw_as_glow = true,
                        shift = util.by_pixel(0, -14.25)
                    }
                }, {
                    fadeout = true,
                    north_animation = {
                        filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery-light.png",
                        width = 321,
                        height = 205,
                        blend_mode = "additive",
                        draw_as_glow = true,
                        shift = util.by_pixel(-1, -50),
                        scale = 0.5
                    },
                    east_animation = {
                        filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery-light.png",
                        width = 321,
                        x = 321,
                        height = 205,
                        blend_mode = "additive",
                        draw_as_glow = true,
                        shift = util.by_pixel(-1, -50),
                        scale = 0.5
                    },
                    south_animation = {
                        filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery-light.png",
                        width = 321,
                        x = 321 * 2,
                        height = 205,
                        blend_mode = "additive",
                        draw_as_glow = true,
                        shift = util.by_pixel(-1, -50),
                        scale = 0.5
                    },
                    west_animation = {
                        filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery-light.png",
                        width = 321,
                        x = 321 * 3,
                        height = 205,
                        blend_mode = "additive",
                        draw_as_glow = true,
                        shift = util.by_pixel(-1, -50),
                        scale = 0.5
                    }
                }}
            },
            impact_category = "metal-large",
            open_sound = sounds.metal_large_open,
            close_sound = sounds.metal_large_close,
            working_sound = {
                sound = {
                    filename = "__base__/sound/oil-refinery.ogg"
                },
                fade_in_ticks = 4,
                fade_out_ticks = 20
            },
            fluid_boxes = {{
                production_type = "input",
                pipe_covers = pipecoverspictures(),
                volume = 1000,
                pipe_connections = {{
                    flow_direction = "input",
                    direction = defines.direction.south,
                    position = {-2, 2}
                }}
            }, {
                production_type = "input",
                pipe_covers = pipecoverspictures(),
                volume = 1000,
                pipe_connections = {{
                    flow_direction = "input",
                    direction = defines.direction.south,
                    position = {0, 2}
                }}
            }, {
                production_type = "input",
                pipe_covers = pipecoverspictures(),
                volume = 1000,
                pipe_connections = {{
                    flow_direction = "input",
                    direction = defines.direction.south,
                    position = {2, 2}
                }}
            }, {
                production_type = "output",
                pipe_covers = pipecoverspictures(),
                volume = 100,
                pipe_connections = {{
                    flow_direction = "output",
                    direction = defines.direction.north,
                    position = {-2, -2}
                }}
            }, {
                production_type = "output",
                pipe_covers = pipecoverspictures(),
                volume = 100,
                pipe_connections = {{
                    flow_direction = "output",
                    direction = defines.direction.north,
                    position = {0, -2}
                }}
            }, {
                production_type = "output",
                pipe_covers = pipecoverspictures(),
                volume = 100,
                pipe_connections = {{
                    flow_direction = "output",
                    direction = defines.direction.north,
                    position = {2, -2}
                }}
            }},
            water_reflection = {
                pictures = {
                    filename = "__space-age-addon__/graphics/entity/advanced-oil-refinery/oil-refinery-reflection.png",
                    priority = "extra-high",
                    width = 40,
                    height = 48,
                    shift = util.by_pixel(5, 95),
                    variation_count = 4,
                    scale = 5
                },
                rotate = false,
                orientation_to_variation = true
            }
        },
        
        ---magmothermic-reactor---
        {
            type = "fusion-reactor",
            name = "magmothermic-reactor",

            icon = "__space-age-addon__/graphics/icons/magmothermic-reactor.png",
            icon_size = 256,
            icon_mipmaps = 4,

            flags = {
                "placeable-neutral",
                "placeable-player",
                "player-creation",
                "not-rotatable"
            },

            minable = {
                mining_time = 0.2,
                result = "magmothermic-reactor"
            },

            max_health = 3500,

            collision_box = {{-2.4, -2.4}, {2.4, 2.4}},
            selection_box = {{-2.5, -2.5}, {2.5, 2.5}},

            graphics_set = {
                structure = {
                    north = {
                        layers = {
                            {
                                filename = "__space-age-addon__/graphics/entity/magmothermic-reactor/magmothermic-reactor.png",
                                priority = "extra-high",
                                width = 444,
                                height = 456,
                                shift = {0, 0},
                                scale = 0.5
                            }
                        }
                    },
                    east = {
                        layers = {
                            {
                                filename = "__space-age-addon__/graphics/entity/magmothermic-reactor/magmothermic-reactor.png",
                                priority = "extra-high",
                                width = 444,
                                height = 456,
                                shift = {0, 0},
                                scale = 0.5
                            }
                        }
                    },
                    south = {
                        layers = {
                            {
                                filename = "__space-age-addon__/graphics/entity/magmothermic-reactor/magmothermic-reactor.png",
                                priority = "extra-high",
                                width = 444,
                                height = 456,
                                shift = {0, 0},
                                scale = 0.5
                            }
                        }
                    },
                    west = {
                        layers = {
                            {
                                filename = "__space-age-addon__/graphics/entity/magmothermic-reactor/magmothermic-reactor.png",
                                priority = "extra-high",
                                width = 444,
                                height = 456,
                                shift = {0, 0},
                                scale = 0.5
                            }
                        }
                    }
                },

                plasma_category = "fusion-plasma"
            },

            energy_source = {
                type = "electric",
                usage_priority = "primary-input"
            },

            power_input = "5MW",

            burner = {
                type = "burner",
                fuel_categories = {"magmatic"},
                effectivity = 1,
                fuel_inventory_size = 1,
                burnt_inventory_size = 1,
                emissions_per_minute = {
                    pollution = 0
                }
            },

            max_fluid_usage = 1200 / 60,

            target_temperature = 750,

            input_fluid_box = {
                production_type = "input",
                volume = 2400,
                filter = "water",

                pipe_covers = pipecoverspictures(),

                pipe_connections = {
                    {
                        flow_direction = "input-output",
                        direction = defines.direction.north,
                        position = {0, -2}
                    },
                    {
                        flow_direction = "input-output",
                        direction = defines.direction.south,
                        position = {0, 2}
                    }
                }
            },

            output_fluid_box = {
                production_type = "output",
                volume = 1200,
                filter = "steam",

                pipe_covers = pipecoverspictures(),
                pipe_picture = assembler3pipepictures(),

                pipe_connections = {
                    {
                        flow_direction = "output",
                        direction = defines.direction.west,
                        position = {-2, 0}
                    },


                    {
                        flow_direction = "output",
                        direction = defines.direction.east,
                        position = {2, 0}
                    }
                }
            }
        },

        ---magmothermic-turbine---
        {
            type = "generator",
            name = "magmothermic-turbine",
            icon = "__space-age-addon__/graphics/icons/magmothermic-turbine.png",
            icon_size = 256,
            icon_mipmaps = 4,
            flags = {
                "placeable-neutral",
                "player-creation",
            },
            minable = {mining_time = 0.3, result = "magmothermic-turbine"},
            max_health = 3000,
            corpse = "steam-turbine-remnants",
            alert_icon_shift = util.by_pixel(0, -12),
            effectivity = 1,
            fluid_usage_per_tick = 10,
            maximum_temperature = 750,
            burns_fluid = false,
            resistances =
            {
                {
                type = "fire",
                percent = 70
                }
            },
            fast_replaceable_group = "steam-engine",
            collision_box = {{-5.4, -2.4}, {5.4, 2.4}},
            selection_box = {{-5.5, -2.5}, {5.5, 2.5}},
            damaged_trigger_effect = hit_effects.entity(),

            horizontal_animation =
            {
                layers =
                {
                {
                    filename = "__space-age-addon__/graphics/entity/magmothermic-turbine/magmothermic-turbine-v2-vertical.png",
                    width = 640,
                    height = 1152,
                    frame_count = 1,
                    line_length = 1,
                    shift = util.by_pixel(0, 0),
                    scale = 0.3214
                }
                }
            },
            vertical_animation =
            {
                layers =
                {
                {
                    filename = "__space-age-addon__/graphics/entity/magmothermic-turbine/magmothermic-turbine-v2.png",
                    width = 1152,
                    height = 640,
                    frame_count = 1,
                    line_length = 1,
                    shift = util.by_pixel(0, 0),
                    scale = 0.3214
                }
                }
            },

            fluid_box =
            {
                volume = 1200,
                pipe_covers = pipecoverspictures(),
                pipe_connections =
                {
                { flow_direction = "input-output", direction = defines.direction.west, position = {-5, 0}, pipe_picture = assembler3pipepictures() },
                { flow_direction = "input-output", direction = defines.direction.east, position = {5, 0}, pipe_picture = assembler3pipepictures() },
                },
                production_type = "input",
                filter = "steam",
                minimum_temperature = 750.0
            },

            energy_source =
            {
                type = "electric",
                usage_priority = "secondary-output"
            },

            impact_category = "metal-large",
            open_sound = sounds.machine_open,
            close_sound = sounds.machine_close,
            working_sound =
            {
                sound =
                {
                filename = "__base__/sound/steam-turbine.ogg",
                volume = 0.49,
                modifiers = volume_multiplier("main-menu", 0.7),
                speed_smoothing_window_size = 60,
                advanced_volume_control = {attenuation = "exponential"},
                audible_distance_modifier = 0.8,
                },
                match_speed_to_activity = true,
                max_sounds_per_prototype = 3,
                fade_in_ticks = 4,
                fade_out_ticks = 20
            },
            perceived_performance = {minimum = 0.25, performance_to_activity_rate = 2.0},
        },

        ------------------------ Манипуляторы ------------------------
        ---bulk-inserter-tier-2---
        {
            type = "inserter",
            name = "bulk-inserter-tier-2",
            icon = "__space-age-addon__/graphics/icons/bulk-inserter-tier-2.png",
            localised_name = {"entity-name.bulk-inserter-tier-2"},
            flags = {"placeable-neutral", "placeable-player", "player-creation"},
            bulk = true,
            minable = {
                mining_time = 0.1,
                result = "bulk-inserter-tier-2"
            },
            max_health = 200,
            stack_size_bonus = 8,
            corpse = "bulk-inserter-remnants",
            dying_explosion = "bulk-inserter-explosion",
            resistances = {{
                type = "fire",
                percent = 90
            }},
            collision_box = {{-0.15, -0.15}, {0.15, 0.15}},
            selection_box = {{-0.4, -0.35}, {0.4, 0.45}},
            damaged_trigger_effect = hit_effects.entity(),
            starting_distance = 0.85,
            pickup_position = {0, -1},
            insert_position = {0, 1.2},
            energy_per_movement = "30kJ",
            energy_per_rotation = "30kJ",
            energy_source = {
                type = "electric",
                usage_priority = "secondary-input",
                drain = "2kW"
            },
            extension_speed = 0.1,
            rotation_speed = 0.05,
            filter_count = 5,
            icon_draw_specification = {
                scale = 0.5
            },
            fast_replaceable_group = "inserter",
            open_sound = sounds.inserter_open,
            close_sound = sounds.inserter_close,
            working_sound = sounds.inserter_fast,
            hand_base_picture = {
                filename = "__space-age-addon__/graphics/entity/bulk-inserter-tier-2/bulk-inserter-hand-base.png",
                priority = "extra-high",
                width = 32,
                height = 136,
                scale = 0.25
            },
            hand_closed_picture = {
                filename = "__space-age-addon__/graphics/entity/bulk-inserter-tier-2/bulk-inserter-hand-closed.png",
                priority = "extra-high",
                width = 100,
                height = 164,
                scale = 0.25
            },
            hand_open_picture = {
                filename = "__space-age-addon__/graphics/entity/bulk-inserter-tier-2/bulk-inserter-hand-open.png",
                priority = "extra-high",
                width = 130,
                height = 164,
                scale = 0.25
            },
            hand_base_shadow = {
                filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
                priority = "extra-high",
                width = 32,
                height = 132,
                scale = 0.25
            },
            hand_closed_shadow = {
                filename = "__space-age-addon__/graphics/entity/bulk-inserter-tier-2/bulk-inserter-hand-closed-shadow.png",
                priority = "extra-high",
                width = 100,
                height = 164,
                scale = 0.25
            },
            hand_open_shadow = {
                filename = "__space-age-addon__/graphics/entity/bulk-inserter-tier-2/bulk-inserter-hand-open-shadow.png",
                priority = "extra-high",
                width = 130,
                height = 164,
                scale = 0.25
            },
            platform_picture = {
                sheet = {
                    filename = "__space-age-addon__/graphics/entity/bulk-inserter-tier-2/bulk-inserter-platform.png",
                    priority = "extra-high",
                    width = 105,
                    height = 79,
                    shift = util.by_pixel(1.5, 7.5 - 1),
                    scale = 0.5
                }
            },
            circuit_connector = circuit_connector_definitions["inserter"],
            circuit_wire_max_distance = inserter_circuit_wire_max_distance,
            default_stack_control_input_signal = inserter_default_stack_control_input_signal
        }
    }
)
